# Generated by Django 4.2.26 on 2025-11-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(help_text='Match ID (e.g., NA1_5302453222)', max_length=50, primary_key=True, serialize=False)),
                ('game_creation', models.BigIntegerField(help_text='Unix timestamp when game was created')),
                ('game_duration', models.IntegerField(help_text='Game duration in seconds')),
                ('game_mode', models.CharField(help_text='Game mode (e.g., CLASSIC, ARAM)', max_length=50)),
                ('game_type', models.CharField(help_text='Game type (e.g., MATCHED_GAME)', max_length=50)),
                ('raw_data', models.JSONField(blank=True, help_text='Full match data from Riot API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['-game_creation'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('puuid', models.CharField(help_text='Player Universal Unique Identifier', max_length=78, primary_key=True, serialize=False)),
                ('game_name', models.CharField(help_text='Riot ID game name', max_length=100)),
                ('tag_line', models.CharField(help_text='Riot ID tag line', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('champion_id', models.IntegerField()),
                ('champion_name', models.CharField(max_length=50)),
                ('champ_level', models.IntegerField(default=1)),
                ('double_kills', models.IntegerField(default=0)),
                ('triple_kills', models.IntegerField(default=0)),
                ('quadra_kills', models.IntegerField(default=0)),
                ('penta_kills', models.IntegerField(default=0)),
                ('total_damage_dealt_to_champions', models.IntegerField(default=0)),
                ('gold_earned', models.IntegerField(default=0)),
                ('total_minions_killed', models.IntegerField(default=0)),
                ('vision_score', models.IntegerField(default=0)),
                ('wards_placed', models.IntegerField(default=0)),
                ('wards_killed', models.IntegerField(default=0)),
                ('kda', models.FloatField(blank=True, help_text='KDA ratio from challenges', null=True)),
                ('kill_participation', models.FloatField(blank=True, help_text='Kill participation percentage', null=True)),
                ('damage_per_minute', models.FloatField(blank=True, null=True)),
                ('gold_per_minute', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='backend.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='backend.player')),
            ],
            options={
                'verbose_name': 'Player Match Stats',
                'verbose_name_plural': 'Player Match Stats',
                'db_table': 'player_match_stats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['game_name', 'tag_line'], name='players_game_na_94460c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-game_creation'], name='matches_game_cr_b71391_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['player', '-created_at'], name='player_matc_player__84c3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['win'], name='player_matc_win_318681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together={('player', 'match')},
        ),
    ]
